title:            Phuong 'J' Le H.
description:      Personal website
logo:             logo.png
disqus_shortname: yeuem1vannam
# Assign a default image for your site's header and footer
default_bg:       bg-code.jpg
search:           true
share:            true
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true
# Specify the average Words per minute. If not defined, 180 will be used
wpm:				      200
# Turn on or off the fin animations in the header and footer
triangleheader:		true
animated_fins:	  true
# Specify the fin color in RGB value
fin_color:        "255,255,255"
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
baseurl: http://yeuem1vannam.github.io
asset_url:

# Owner/author information
owner:
  name:           Le Hoai Phuong
  avatar:         my_avatar.png
  email:          phuonglh0420@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Awesome!
  # Social networking links used in footer. Update and remove as you like.
  twitter:        yeuem1vannam
  facebook:       yeuem1vannam
  github:         yeuem1vannam
  # stackexchange:  https://stackexchange.com/users/3402032/hossain-mohd-faysal
  stackexchange: https://stackexchange.com/users/1918794/yeuem1vannam
  # linkedin:       https://www.linkedin.com/pub/firstname-lastname/12/345/678
  linkedin: https://vn.linkedin.com/in/yeuem1vannam
  # instagram:
  # flickr:
  # tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:   https://plus.google.com/u/0/102717131394874333583

# Analytics and webmaster tools stuff goes here
google_analytics: UA-48013823-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  # - title: Documentation
  #   url: /documentation
  #   icon: book
  - title: Categories
    url: /categories
  - title: Tags
    url: /tags
  - title: About me
    url: /about
  - title: Privacy Policy
    url: /privacy-policy
  - title: Terms and Conditions
    url: /terms-and-conditions

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Ho_Chi_Minh
future:      true
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - strikethrough
    - lax_spacing
    - space_after_headers
    - superscript
    - underline
    - highlight
    - quote
    - footnotes
    - tables
    # - link_attributes
    # - with_toc_data
paginate:    3
paginate_path: "/page/:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
